
<strong><center>DataContainer</center></strong>

* Generic class to hold data. 

* Currently wraps numpy arrays.  In future release, we plan to create a GPUDataContainer and BoostDataContainer which will hold the data in an array on GPU or in a boost multidimensional array respectively.

* Basic algebraic methods are implemented  between each other and/or with numbers. 

In [1]:
import numpy as np
from ccpi.framework import DataContainer

In [2]:
# Create numpy data
a = np.array([2,3,4])
b = np.random.randint(10,size = (4,5))

# Wrap them as DataContainers
A = DataContainer(a)
B = DataContainer(b)

In [3]:
print('Details of DataContainer A: \n{}'.format(A))
print('Details of DataContainer B: \n{}'.format(B))

Details of DataContainer A: 
Number of dimensions: 1
Shape: (3,)
Axis labels: {0: 'dimension_00'}

Details of DataContainer B: 
Number of dimensions: 2
Shape: (4, 5)
Axis labels: {0: 'dimension_00', 1: 'dimension_01'}



In [4]:
# Show DataContainer Code
A??

In [5]:
# Get back numpy arrays
print('A = {}'.format(A.as_array()))
print('B = {}'.format(B.as_array()))

A = [2 3 4]
B = [[8 5 5 5 6]
 [3 4 0 9 1]
 [0 1 2 1 2]
 [6 8 8 2 7]]


In [6]:
# change labels name
C = B.copy()

C.dimension_labels[0] = ' y '
C.dimension_labels[1] = ' x '
print('Details of DataContainer B: \n{}'.format(B))
print('Details of DataContainer C: \n{}'.format(C))


Details of DataContainer B: 
Number of dimensions: 2
Shape: (4, 5)
Axis labels: {0: 'dimension_00', 1: 'dimension_01'}

Details of DataContainer C: 
Number of dimensions: 2
Shape: (4, 5)
Axis labels: {0: ' y ', 1: ' x '}



<strong><center>ImageData and AcquisitionData</center></strong>
    
    
* ImageData and AcquisitionData are subclasses of DataContainer 
* Contain 2D - 4D data and raw data along with their geometries i.e.,
    1. <strong>ImageGeometry<strong>  
    2. <strong>AcquisitionGeometry<strong>
    

* Here, we create ImageGeometries and their corresponding ImageData.
* We can also recover an ImageGeometry if we load a TestData.
* TestData contains the following:

     1. BOAT = 'boat.tiff'
     2. CAMERA = 'camera.png'
     3. PEPPERS = 'peppers.tiff'
     4. RESOLUTION_CHART = 'resolution_chart.tiff'
     5. SIMPLE_PHANTOM_2D = 'hotdog'
     6. SHAPES =  'shapes.png'


    

In [11]:
from ccpi.framework import ImageData, ImageGeometry

# Define 2D ImageGeometry
ig = ImageGeometry(voxel_num_y = 5, voxel_num_x = 4)

# Create random ImageData with the specific geometry
im_data1 = ig.allocate()
im_data2 = ig.allocate('random', seed = 5)

In [12]:
print('Allocate with zeros \n{}\n'.format(im_data1.as_array()))
print('Allocate with random numbers in [0,1] \n{}\n'.format(im_data2.as_array()))
print('Dimensions and Labels = {} , {}'.format(im_data1.shape, im_data1.dimension_labels))

Allocate with zeros 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Allocate with random numbers in [0,1] 
[[0.22199318 0.8707323  0.20671916 0.91861093]
 [0.4884112  0.61174387 0.7659079  0.518418  ]
 [0.2968005  0.18772122 0.08074127 0.7384403 ]
 [0.4413092  0.15830986 0.87993705 0.27408648]
 [0.41423503 0.29607993 0.62878793 0.5798378 ]]

Dimensions and Labels = (5, 4) , {0: 'horizontal_y', 1: 'horizontal_x'}


In [13]:
# Define 2D + channels ImageGeometry
ig1 = ImageGeometry(voxel_num_y = 5, voxel_num_x = 4, channels = 2)

# Create random integer in [0, max_value] ImageData with the specific geometry
im_data3 = ig1.allocate('random_int', seed = 10, max_value = 500)

print('Allocate with random integers \n{}\n'.format(im_data3.as_array()))
print('Dimensions and Labels =  {}'.format(im_data3.get_shape_labels(ig1)))

Allocate with random integers 
[[[265. 125. 484.  15.]
  [320. 369. 123. 156.]
  [473. 221. 496. 413.]
  [369.   8.  73. 256.]
  [490.  40. 420. 371.]]

 [[ 16. 356. 239. 395.]
  [ 54. 344. 363. 122.]
  [ 62.  33. 200. 356.]
  [462. 177. 179.  54.]
  [ 77. 453.  13. 243.]]]

Dimensions and Labels =  ((2, 5, 4), ['channel', 'horizontal_y', 'horizontal_x'])


In [14]:
# import TestData and recover geometry

from ccpi.framework import TestData
import os, sys

loader = TestData(data_dir=os.path.join(sys.prefix, 'share','ccpi'))

data = loader.load(TestData.SHAPES, size=(50,50))
ig2 = data.geometry

print(ig2)


# TODO size for shapes is wrong, either fix it or allow resize
# TODO remove data print in loader.load

data.geometry Number of channels: 1
voxel_num : x200,y300,z0
voxel_size : x1,y1,z1
center : x0,y0,z0

Number of channels: 1
voxel_num : x200,y300,z0
voxel_size : x1,y1,z1
center : x0,y0,z0

